# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tab0.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial

class SearchTab(QtWidgets.QWidget):
    def __init__(self):
        super(SearchTab, self).__init__()
        font = QtGui.QFont()
        font.setPointSize(14)
        #Form.setFont(font)
        layout = QtWidgets.QVBoxLayout()
        self.setLayout(layout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_SLP = QtWidgets.QLineEdit()
        self.input_SLP.setObjectName("input_SLP")
        self.horizontalLayout.addWidget(self.input_SLP)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.input_caseID = QtWidgets.QLineEdit()
        self.input_caseID.setObjectName("input_caseID")
        self.horizontalLayout_2.addWidget(self.input_caseID)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.input_Name = QtWidgets.QLineEdit()
        self.input_Name.setObjectName("input_Name")
        self.horizontalLayout_3.addWidget(self.input_Name)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.searchBtn = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.searchBtn.clicked.connect(self._search)
        self.horizontalLayout_4.addWidget(self.searchBtn)
        layout.addLayout(self.horizontalLayout_4)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        layout.addItem(spacerItem)

        self.tableWidget = QtWidgets.QTableWidget()
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)

        layout.addWidget(self.tableWidget)
        self.retranslateUi()

    def _search(self):
        '''
        cursor = 呼叫的api
        for idx, doc in enumerate(cursor):
            self.tableWidget.insertRow(idx)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(idx,0) = doc['include.SLP']
            self.tableWidget.setItem(idx,1) = ...
            ...
            ...
            importBtn = QtWidgets.QPushButton('匯入')
            deleteBtn = QtWidgets.QPushButton('刪除')
            self.tableWidget.setCellWidget(idx,7,importBtn)
            self.tableWidget.setCellWidget(idx,8,deleteBtn)
            importBtn.clicked.connect(partial(self.importDoc, doc['objID']))
            deleteBtn.clicked.connect(partial(self.deleteDoc, doc['objID']))
        '''

    def importDoc(self,objID):
        pass

    def deleteDoc(self,objID):
        pass

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "收錄者："))
        self.label_2.setText(_translate("Form", "個案編號："))
        self.label_3.setText(_translate("Form", "個案姓名："))
        self.searchBtn.setText(_translate("Form", "查詢"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "收錄者"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "個案編號"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "個案姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "收錄日期"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "收錄情境"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "收錄地點"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "收錄題材"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    screen = SearchTab()
    screen.show()
    sys.exit(app.exec_())
