# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'myself.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import database.DBapi
from datetime import datetime
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import win32api

class BirthdayEdit(QtWidgets.QDateEdit):
    def __init__(self, parent=None):
        super().__init__(parent, calendarPopup=True)

class DateEdit(QtWidgets.QDateTimeEdit):
    def __init__(self, parent=None):
        super().__init__(parent, calendarPopup=True)
        self.setDateTime(QtCore.QDateTime.currentDateTime())
        self.setDisplayFormat("yyyy-MM-dd HH:mm")

class Myform(QtWidgets.QWidget):
    procStart = QtCore.pyqtSignal(dict)

    def __init__(self):
        super(Myform, self).__init__()
        self.setObjectName("self")

        layout = QtWidgets.QVBoxLayout()
        self.setLayout(layout)
        
        self.resize(1393, 815)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.setFont(font)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(830, 400, 301, 71))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self)        
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(200, 410, 931, 51))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_19.addWidget(self.checkBox_5)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_19.addWidget(self.checkBox_3)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_19.addWidget(self.checkBox_6)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_19.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_19.addWidget(self.checkBox_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_15.addWidget(self.checkBox_7)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_19)
        self.lineEdit_10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_15.addWidget(self.lineEdit_10)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_15)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_15.addWidget(self.lineEdit_10)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(251, 591, 1011, 61))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_17.addWidget(self.plainTextEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(61, 111, 141, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(640, 50, 349, 49))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(600, 350, 301, 51))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(200, 290, 331, 71))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_9.addWidget(self.lineEdit_7)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(201, 110, 211, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        #收錄者姓名
        self.lineEdit.setObjectName("lineEdit") 
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(450, 100, 251, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3) #個案編號
        self.lineEdit_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(31, 511, 221, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(600, 300, 681, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_8.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_8.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_8.addWidget(self.radioButton_9)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(580, 160, 301, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5) 
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_5.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_5.addWidget(self.radioButton_2)
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(200, 450, 931, 81))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.radioButton_11 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_20.addWidget(self.radioButton_11)
        self.radioButton_10 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_20.addWidget(self.radioButton_10)
        self.radioButton_12 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_20.addWidget(self.radioButton_12)
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(251, 671, 1011, 56))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_21)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.horizontalLayout_21.addWidget(self.plainTextEdit_2)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(200, 340, 331, 71))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_10.addWidget(self.lineEdit_12)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(251, 521, 881, 51))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radioButton_15 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_16.addWidget(self.radioButton_15)
        self.radioButton_17 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_17.setFont(font)
        self.radioButton_17.setObjectName("radioButton_17")
        self.horizontalLayout_16.addWidget(self.radioButton_17)
        self.radioButton_16 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout_16.addWidget(self.radioButton_16)
        self.radioButton_14 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_16.addWidget(self.radioButton_14)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(201, 151, 211, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3") #個案姓名
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(1050, 160, 221, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.dateEdit = BirthdayEdit()
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(980, 340, 291, 61))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(200, 240, 331, 61))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_22)
        self.lineEdit_11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_22.addWidget(self.lineEdit_11)
        self.label_25 = QtWidgets.QLabel(self)
        self.label_25.setGeometry(QtCore.QRect(890, 110, 139, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(960, 160, 111, 49))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(750, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.searchCaseID)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(1050, 110, 221, 51))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")

        self.dateEdit_3 = DateEdit()
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.horizontalLayout_11.addWidget(self.dateEdit_3)
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(20, 220, 1351, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 240, 141, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(600, 240, 381, 61))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_18)
        self.lineEdit_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_23.addWidget(self.lineEdit_14)
         #儲存資料的按鈕
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(1080, 750, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.save)

        self.retranslateUi()
        self.saveForm = self.returnTab1Data()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.checkBox_7.setText(_translate("self", " 其他"))
        self.label_21.setText(_translate("self", "收錄者:"))
        self.label_22.setText(_translate("self", "個案姓名:"))
        self.label_3.setText(_translate("self", "CLSA分析"))
        self.label_14.setText(_translate("self", "兒童總語句數:"))
        self.label_2.setText(_translate("self", "個案編號:"))
        self.label_20.setText(_translate("self", "需要引導協助:"))
        self.label_19.setText(_translate("self", "其他特殊情況:"))
        self.label_18.setText(_translate("self", "兒童焦慮情形:"))
        self.checkBox_5.setText(_translate("self", " 老師"))
        self.checkBox_3.setText(_translate("self", "爸爸"))
        self.checkBox_6.setText(_translate("self", "媽媽"))
        self.checkBox_4.setText(_translate("self", "施測者"))
        self.checkBox_2.setText(_translate("self", " 兒童"))
        self.label_8.setText(_translate("self", "互動形式:"))
        self.radioButton_7.setText(_translate("self", "交談"))
        self.radioButton_8.setText(_translate("self", "自由遊戲"))
        self.radioButton_9.setText(_translate("self", "敘事"))
        self.label_5.setText(_translate("self", "性別:"))
        self.radioButton.setText(_translate("self", "男"))
        self.radioButton_2.setText(_translate("self", "女"))
        self.radioButton_11.setText(_translate("self", "其他錄音設備"))
        self.radioButton_10.setText(_translate("self", "錄音筆"))
        self.radioButton_12.setText(_translate("self", "攝影機"))
        self.radioButton_15.setText(_translate("self", "很少 (幾乎不需要引導)"))
        self.radioButton_17.setText(_translate("self", "有時 (2~5次)"))
        self.radioButton_16.setText(_translate("self", "經常 (6~9次)"))
        self.radioButton_14.setText(_translate("self", "總是"))
        self.label_15.setText(_translate("self", "有效語句數:"))
        self.pushButton.setText(_translate("self", "儲存資料"))
        self.label_25.setText(_translate("self", "收錄日期:"))
        self.label_6.setText(_translate("self", "生日:"))
        self.pushButton_2.setText(_translate("self", "查詢"))
        self.label_23.setText(_translate("self", "收錄情境:"))
        self.label_24.setText(_translate("self", "收錄地點:"))
        self.label_16.setText(_translate("self", "誘發題材:"))
        self.label_26.setText(_translate("self", "參與人員:"))
        self.label_17.setText(_translate("self", "記錄方式:"))
        self.label_28.setText(_translate("self", "錄影／錄音檔名"))
        
    #接收來自Tab2的總語句數與有效語句數
    @QtCore.pyqtSlot(dict)
    def getUtterNum(self, utterance) :
        if utterance == None:
            return
        self.label.setText(str(utterance['totalUtterance']))
        self.label_4.setText(str(utterance['validUtterance']))

    #傳個案編號到Tab2
    @QtCore.pyqtSlot() 
    def sendCaseID(self, caseIDandDate):
        self.procStart.emit(caseIDandDate)

    #查詢個案編號並把個案資料貼到Tab1
    def searchCaseID(self): 
        caseData = database.DBapi.findChildData(self.lineEdit_2.text())
        print (caseData)
        if caseData:
            self.lineEdit_3.setText(caseData['name'])
            if caseData['gender'] == 'male':
                self.radioButton.setChecked(True)
            else :
                self.radioButton_2.setChecked(True)
            self.dateEdit.setDate(caseData['birthday'])
        else :
            win32api.MessageBox(0, '查無此個案資料', '提示')
    
    #回傳現在Tab1的所有資料
    def returnTab1Data (self) :
        #判斷是男是女
        if self.radioButton.isChecked():
            gender = 'male'
        else :
            gender = 'female'

        #將dateEdit變成dateTime型態
        date = str(self.dateEdit.date().toPyDate())
        birthday = datetime.strptime(date, "%Y-%m-%d")

        #將dateEdit_3變成dateTime型態
        strDate = str(self.dateEdit_3.dateTime().toPyDateTime())
        DateTimeDate = datetime.strptime(strDate, "%Y-%m-%d %H:%M:%S.%f")
        strRecordDate = DateTimeDate.strftime("%Y-%m-%d %H:%M:%S")
        DateTimeRecordDate = datetime.strptime(strRecordDate, "%Y-%m-%d %H:%M:%S")

        #判斷互動形式   
        form = ''
        if self.radioButton_7.isChecked():
            form = '交談'
        if self.radioButton_8.isChecked():
            form = '自由遊戲'
        if self.radioButton_9.isChecked():
            form = '敘事'
        
        #判斷記錄方式
        recordType = ''
        if self.radioButton_10.isChecked():
            recordType = '錄音筆'
        if self.radioButton_11.isChecked():
            recordType = '其他錄音設備'
        if self.radioButton_12.isChecked():
            recordType = '攝影機'

        #判斷需要引導協助
        needhelp = ''
        if self.radioButton_14.isChecked():
            needhelp = '總是'
        if self.radioButton_15.isChecked():
            needhelp = '很少 (幾乎不需要引導)'
        if self.radioButton_16.isChecked():
            needhelp = '經常 (6~9次)'
        if self.radioButton_17.isChecked():
            needhelp = '有時 (2~5次)'

        #判斷參與人員
        participants = []
        if self.checkBox_2.isChecked():
            participants.append("兒童")
        if self.checkBox_3.isChecked():
            participants.append("爸爸")
        if self.checkBox_4.isChecked():
            participants.append("施測者")
        if self.checkBox_5.isChecked():
            participants.append("老師")
        if self.checkBox_6.isChecked():
            participants.append("媽媽")
        if self.checkBox_7.isChecked() and self.lineEdit_10.text():
            participants.append(self.lineEdit_10.text())
        
        data = {
            'caseID' : self.lineEdit_2.text(),
            'name': self.lineEdit_3.text(),
            'gender' : gender,
            'birthday' : birthday,
            'date' : DateTimeRecordDate,
            'SLP': self.lineEdit.text(),
            'scenario': self.lineEdit_11.text(),
            'fileName' : self.lineEdit_14.text(),
            'location' : self.lineEdit_7.text(),
            'form' : form,
            'inducement' : self.lineEdit_12.text(),
            'participants' : participants,
            'recordType' :recordType,
            'help' : needhelp,
            'others' : self.plainTextEdit.toPlainText(),
            'situation' : self.plainTextEdit_2.toPlainText()
        }
        return data
        
    #儲存資料到資料庫 
    def save (self): 
        error = 0

        #收錄者
        if not self.lineEdit.text(): 
            error+=1
            self.lineEdit.setStyleSheet("border: 1px solid red;" )
        else :
            self.lineEdit.setStyleSheet("border: 1px solid initial;" )
        
        #個案編號
        if not self.lineEdit_2.text(): 
            error+=1
            self.lineEdit_2.setStyleSheet("border: 1px solid red;" )
        else :
            self.lineEdit_2.setStyleSheet("border: 1px solid initial;" )
        
        #個案姓名
        if not self.lineEdit_3.text(): 
            error+=1
            self.lineEdit_3.setStyleSheet("border: 1px solid red;")
        else:
            self.lineEdit_3.setStyleSheet("border: 1px solid initial;" )
        
        #性別
        if not (self.radioButton.isChecked() or self.radioButton_2.isChecked()): 
            error += 1
            self.horizontalLayoutWidget_5.setStyleSheet("border: 1px solid red;")
            self.radioButton.setStyleSheet("border: 1px;")
            self.radioButton_2.setStyleSheet("border: 1px;")
            self.label_5.setStyleSheet("border: 1px;")
        else:
            self.horizontalLayoutWidget_5.setStyleSheet("border: 1px;")
        
        #收錄地點
        if not self.lineEdit_7.text(): 
            error +=1
            self.lineEdit_7.setStyleSheet("border: 1px solid red;")
        else:
            self.lineEdit_7.setStyleSheet("border: 1px solid initial;")
        
        #收錄情境
        if not self.lineEdit_11.text(): 
            error += 1
            self.lineEdit_11.setStyleSheet("border: 1px solid red;")
        else :
            self.lineEdit_11.setStyleSheet("border: 1px solid initial;")
        
        #互動形式
        if not (self.radioButton_7.isChecked() or self.radioButton_8.isChecked() or self.radioButton_9.isChecked()):
            error += 1
            self.horizontalLayoutWidget_8.setStyleSheet("border: 1px solid red;")
            self.radioButton_7.setStyleSheet("border: 1px;")
            self.radioButton_8.setStyleSheet("border: 1px;")
            self.radioButton_9.setStyleSheet("border: 1px;")
            self.label_8.setStyleSheet("border: 1px;")
        else :
            self.horizontalLayoutWidget_8.setStyleSheet("border: 1px;")
        
        #參與人員
        if not (self.checkBox_2.isChecked() or self.checkBox_3.isChecked() or self.checkBox_4.isChecked() or self.checkBox_5.isChecked() or self.checkBox_6.isChecked() or self.checkBox_7.isChecked()):
            error +=1
            self.horizontalLayoutWidget_19.setStyleSheet("border: 1px solid red;")
            self.checkBox_2.setStyleSheet("border: 1px;")
            self.checkBox_3.setStyleSheet("border: 1px;")
            self.checkBox_4.setStyleSheet("border: 1px;")
            self.checkBox_5.setStyleSheet("border: 1px;")
            self.checkBox_6.setStyleSheet("border: 1px;")
            self.checkBox_7.setStyleSheet("border: 1px;")
            self.lineEdit_10.setStyleSheet("border: 1px;")
        else :
            self.horizontalLayoutWidget_19.setStyleSheet("border: 1px;")

        #誘發題材
        if not self.lineEdit_12.text():
            error += 1
            self.lineEdit_12.setStyleSheet("border: 1px solid red;")
        else :
            self.lineEdit_12.setStyleSheet("border: 1px solid initial;")

        #錄影錄音檔名
        if not self.lineEdit_14.text():
            error += 1
            self.lineEdit_14.setStyleSheet("border: 1px solid red;")
        else :
            self.lineEdit_14.setStyleSheet("border: 1px solid initial;")
        
        #其他特殊情況
        if not self.plainTextEdit.toPlainText():
            error +=1
            self.plainTextEdit.setStyleSheet("border: 1px solid red;")
        else :
            print(self.plainTextEdit.toPlainText())
            self.plainTextEdit.setStyleSheet("border: 1px solid initial;")

        #需要引導協助
        if not (self.radioButton_14.isChecked()  or self.radioButton_15.isChecked() or self.radioButton_16.isChecked() or self.radioButton_17.isChecked()):
            error +=1
            self.horizontalLayoutWidget_16.setStyleSheet("border: 1px solid red;")
            self.radioButton_14.setStyleSheet("border: 1px;")
            self.radioButton_15.setStyleSheet("border: 1px;")
            self.radioButton_16.setStyleSheet("border: 1px;")
            self.radioButton_17.setStyleSheet("border: 1px;")
        else :
            self.horizontalLayoutWidget_16.setStyleSheet("border: 1px;")


        #如果有必填欄位沒填跳提示視窗
        if  error > 0: 
            print ("save fail")
            win32api.MessageBox(0, '紅色框為必填欄位', '警告')
            return False
        else :
            #將dateEdit變成dateTime型態
            date = str(self.dateEdit.date().toPyDate())
            birthday = datetime.strptime(date, "%Y-%m-%d")
            
            #將dateEdit_3變成dateTime型態
            strDate = str(self.dateEdit_3.dateTime().toPyDateTime())
            DateTimeDate = datetime.strptime(strDate, "%Y-%m-%d %H:%M:%S.%f")
            strRecordDate = DateTimeDate.strftime("%Y-%m-%d %H:%M:%S")
            DateTimeRecordDate = datetime.strptime(strRecordDate, "%Y-%m-%d %H:%M:%S")
        

            #判斷是男是女
            gender = ''
            if self.radioButton.isChecked():
                gender = 'male'
            else :
                gender = 'female'

            form = ''
            #判斷互動形式
            if self.radioButton_7.isChecked():
                form = '交談'
            if self.radioButton_8.isChecked():
                form = '自由遊戲'
            if self.radioButton_9.isChecked():
                form = '敘事'

            recordType = ''
            #判斷記錄方式
            if self.radioButton_10.isChecked():
                recordType = '錄音筆'
            if self.radioButton_11.isChecked():
                recordType = '其他錄音設備'
            if self.radioButton_12.isChecked():
                recordType = '攝影機'

            needhelp = ''
            #判斷需要引導協助
            if self.radioButton_14.isChecked():
                needhelp = '總是'
            if self.radioButton_15.isChecked():
                needhelp = '很少 (幾乎不需要引導)'
            if self.radioButton_16.isChecked():
                needhelp = '經常 (6~9次)'
            if self.radioButton_17.isChecked():
                needhelp = '有時 (2~5次)'

            #判斷參與人員
            participants = []
            if self.checkBox_2.isChecked():
                participants.append("兒童")
            if self.checkBox_3.isChecked():
                participants.append("爸爸")
            if self.checkBox_4.isChecked():
                participants.append("施測者")
            if self.checkBox_5.isChecked():
                participants.append("老師")
            if self.checkBox_6.isChecked():
                participants.append("媽媽")
            if self.checkBox_7.isChecked() and self.lineEdit_10.text():
                participants.append(self.lineEdit_10.text())
            
            childData = {
                'caseID' : self.lineEdit_2.text(),
                'name': self.lineEdit_3.text(),
                'gender' : gender,
                'birthday' : birthday
            }
            include = {
                'date' : DateTimeRecordDate,
                'SLP': self.lineEdit.text(),
                'scenario': self.lineEdit_11.text(),
                'fileName' : self.lineEdit_14.text(),
                'location' : self.lineEdit_7.text(),
                'form' : form,
                'inducement' : self.lineEdit_12.text(),
                'participants' : participants,
                'recordType' :recordType,
                'help' : needhelp,
                'others' : self.plainTextEdit.toPlainText(),
                'situation' : self.plainTextEdit_2.toPlainText()
            }
            if database.DBapi.upsertChildAndInclude(childData, include) :
                saveForm = self.returnTab1Data()
                print (saveForm)
                win32api.MessageBox(0, '新增成功', '提示')
                caseIDandDate = {'caseID':self.lineEdit_2.text(), 'date':DateTimeRecordDate}
                self.procStart.emit(caseIDandDate)
                return True
            else :
                saveForm = self.returnTab1Data()
                print (saveForm)
                win32api.MessageBox(0, '新增失敗', '提示')
                return False
    
    #檢查是否有變更
    def saveExamination (self) :
        tab1Changed = self.returnTab1Data()
        if tab1Changed == self.saveForm :
            return False
        else :
            return True 

    #接收來自Tab2的所有資料
    @QtCore.pyqtSlot(dict)
    def getDoc(self, Doc) :
        #設定childData
        if Doc == None:
            return
        self.lineEdit_2.setText(Doc['childData']['caseID'])
        self.lineEdit_3.setText(Doc['childData']['name'])
        if Doc['childData']['gender'] == '男':
            self.radioButton.setChecked(True)
        else :
            self.radioButton_2.setChecked(True)
        self.dateEdit.setDate(Doc['childData']['birthday'])

        #設定include
        self.dateEdit_3.setDateTime(Doc['include']['date'])
        self.lineEdit.setText(Doc['include']['SLP'])
        self.lineEdit_11.setText(Doc['include']['scenario'])
        self.lineEdit_14.setText(Doc['include']['fileName'])
        self.lineEdit_7.setText(Doc['include']['location'])
        if Doc['include']['form'] == '交談':
            self.radioButton_7.setChecked(True)
        if Doc['include']['form'] == '自由遊戲':
            self.radioButton_8.setChecked(True)
        if Doc['include']['form'] == '敘事' :
            self.radioButton_9.setChecked(True)

        self.lineEdit_12.setText(Doc['include']['inducement'])
        
        if Doc['include']['recordType'] == '其他錄音設備':
            self.radioButton_11.setChecked(True)
        if Doc['include']['recordType'] == '錄音筆' :
            self.radioButton_10.setChecked(True)
        if Doc['include']['recordType'] == '攝影機' :
            self.radioButton_12.setChecked(True)
        
        if Doc['include']['help'] == '總是':
            self.radioButton_14.setChecked(True)
        if Doc['include']['help'] == '很少 (幾乎不需要引導)':
            self.radioButton_15.setChecked(True)
        if Doc['include']['help'] == '經常 (6~9次)':
            self.radioButton_16.setChecked(True)
        if Doc['include']['help'] == '有時 (2~5次)':
            self.radioButton_17.setChecked(True)
        self.plainTextEdit.setPlainText(Doc['include']['others'])
        self.plainTextEdit_2.setPlainText(Doc['include']['situation'])

        for i in Doc['include']['participants'] :
            if i == '兒童' :
                self.checkBox_2.setChecked(True)
            elif i == '爸爸' :
                self.checkBox_3.setChecked(True)
            elif i == '施測者' :
                self.checkBox_4.setChecked(True)
            elif i == '老師' :
                self.checkBox_5.setChecked(True)
            elif i == '媽媽' :
                self.checkBox_6.setChecked(True)
            else :
                self.checkBox_7.setChecked(True)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = Myform()
    ui.show()
    sys.exit(app.exec_())
