import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Analysis(QtWidgets.QWidget):
    def __init__(self):
        super(Analysis, self).__init__()
        # self.setObjectName("Form")
        # self.resize(1080, 868)
        layout = QtWidgets.QGridLayout()
        self.setLayout(layout)
        #initial Bold font
        font = QtGui.QFont()
        font.setBold(True)
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setGeometry(QtCore.QRect(270, 30, 481, 761))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(24)
        layout.addWidget(self.tableWidget, 0, 0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter) #字置中
        item.setFont(font) #Bold
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item.setTextAlignment(QtCore.Qt.AlignCenter) #字置中
        item.setFont(font) #Bold
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter) #字置中置頂
        item.setFont(font) #Bold
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter) #字置中置頂
        item.setFont(font) #Bold
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter) #字置中置頂
        item.setFont(font) #Bold
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter) #字置中置頂
        item.setFont(font) #Bold
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.retranslateUi()
        #setSpan
        self.tableWidget.setSpan(0,0,1,3)
        self.tableWidget.setSpan(1,0,2,2)
        self.tableWidget.setSpan(3,0,2,2)
        self.tableWidget.setSpan(5,0,8,1)
        self.tableWidget.setSpan(5,1,8,1)
        self.tableWidget.setSpan(13,0,5,1)
        self.tableWidget.setSpan(13,1,5,1)
        self.tableWidget.setSpan(18,0,2,2)
        self.tableWidget.setSpan(20,0,2,2)
        self.tableWidget.setSpan(22,0,2,2)
        self.tableWidget.setSpan(3,2,2,2)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        #self.tableWidget.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        #self.tableWidget.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        #QtCore.QMetaObject.connectSlotsByName(Form)
        # 設字置中
        for i in range(1,24):
            if i == 3 or i == 4:
                continue
            else:
                self.tableWidget.item(i,2).setTextAlignment(QtCore.Qt.AlignCenter)

    @QtCore.pyqtSlot(list)
    def getChildUtterance(self, utterance):
        pass

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        #Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "兒童語言樣本各指標"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Form", "分析結果"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "1.計算總字數及詞數"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "總字數"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "總詞數"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "3.計算實詞和虛詞"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "2.計算各類詞類數\n（200 個詞中之個數）"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "實詞"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "名詞（N）"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form", "動詞（V）"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Form", "形容詞（A）"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Form", "數詞（Neu）"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Form", "量詞（Nf）"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Form", "代詞（Nh）"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Form", "副詞（D）"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Form", "實詞之總百分比"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("Form", "虛詞"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("Form", "介詞（P）"))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("Form", "連詞（C）"))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("Form", "助詞（T）"))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("Form", "嘆詞（I）"))
        item = self.tableWidget.item(17, 2)
        item.setText(_translate("Form", "虛詞之總百分比"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("Form", "4.計算詞彙多樣性/字的多樣性"))
        item = self.tableWidget.item(18, 2)
        item.setText(_translate("Form", "VOCD-w"))
        item = self.tableWidget.item(19, 2)
        item.setText(_translate("Form", "VOCD-c"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("Form", "5.計算平均語句長度（MLU）"))
        item = self.tableWidget.item(20, 2)
        item.setText(_translate("Form", "MLU-w"))
        item = self.tableWidget.item(21, 2)
        item.setText(_translate("Form", "MLU-c"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("Form", "6.計算最長五個語句之平均語句長度（MLU5）"))
        item = self.tableWidget.item(22, 2)
        item.setText(_translate("Form", "MLU5-w"))
        item = self.tableWidget.item(23, 2)
        item.setText(_translate("Form", "MLU5-c"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    screen = Analysis()
    screen.show()
    sys.exit(app.exec_())
