# font = QtGui.QFont()
#         font.setPointSize(14)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         #Form.setFont(font)
#         layout = QtWidgets.QVBoxLayout()
#         self.setLayout(layout)
#         self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_4.setObjectName("horizontalLayout_4")
#         self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_2.setObjectName("horizontalLayout_2")
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.label = QtWidgets.QLabel()
#         font = QtGui.QFont()
#         font.setPointSize(14)
#         self.label.setFont(font)
#         self.label.setObjectName("label")
#         self.horizontalLayout.addWidget(self.label)
#         self.input_SLP = QtWidgets.QLineEdit()
#         self.input_SLP.setObjectName("input_SLP")
#         self.input_SLP.setSizePolicy(sizePolicy)
#         self.input_SLP.setFont(font)
#         self.horizontalLayout.addWidget(self.input_SLP)
#         self.horizontalLayout_2.addLayout(self.horizontalLayout)
#         self.label_2 = QtWidgets.QLabel()
#         font = QtGui.QFont()
#         font.setPointSize(14)
#         self.label_2.setFont(font)
#         self.label_2.setObjectName("label_2")
#         self.horizontalLayout_2.addWidget(self.label_2)
#         self.input_caseID = QtWidgets.QLineEdit()
#         self.input_caseID.setObjectName("input_caseID")
#         self.input_caseID.setSizePolicy(sizePolicy)
#         self.input_caseID.setFont(font)
#         self.horizontalLayout_2.addWidget(self.input_caseID)
#         self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_3.setObjectName("horizontalLayout_3")
#         self.label_3 = QtWidgets.QLabel()
#         font = QtGui.QFont()
#         font.setPointSize(14)
#         self.label_3.setFont(font)
#         self.label_3.setObjectName("label_3")
#         self.horizontalLayout_3.addWidget(self.label_3)
#         self.input_Name = QtWidgets.QLineEdit()
#         self.input_Name.setObjectName("input_Name")
#         self.input_Name.setSizePolicy(sizePolicy)
#         self.input_Name.setFont(font)
#         self.horizontalLayout_3.addWidget(self.input_Name)
#         self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
#         spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.horizontalLayout_4.addItem(spacerItem)
#         self.searchBtn = QtWidgets.QPushButton()
#         font = QtGui.QFont()
#         font.setPointSize(14)
#         self.searchBtn.setFont(font)
#         self.searchBtn.setObjectName("searchBtn")
#         self.searchBtn.clicked.connect(self._search)
#         self.searchBtn.setToolTip('若輸入皆為空白，可查詢所有個案')
#         self.horizontalLayout_4.addWidget(self.searchBtn)
#         self.horizontalLayout_4.addItem(spacerItem)
#         layout.addLayout(self.horizontalLayout_4)